#
# Makefile
#

CIRCLEHOME = ../..

OBJS	= 	main.o kernel.o display.o filesystem.o gfx.o global.o io.o memory.o menu.o parser.o util.o

LIBS	= 	$(CIRCLEHOME)/lib/usb/libusb.a \
	  		$(CIRCLEHOME)/lib/input/libinput.a \
	  		$(CIRCLEHOME)/addon/SDCard/libsdcard.a \
	  		$(CIRCLEHOME)/lib/fs/fat/libfatfs.a \
	  		$(CIRCLEHOME)/lib/fs/libfs.a \
	  		$(CIRCLEHOME)/lib/libcircle.a \
	  		$(CIRCLEHOME)/lib/sched/libsched.a \
	  		$(CIRCLEHOME)/addon/vc4/interface/bcm_host/libbcm_host.a \
	  		$(CIRCLEHOME)/addon/vc4/interface/khronos/libkhrn_client.a \
	  		$(CIRCLEHOME)/addon/vc4/interface/vmcs_host/libvmcs_host.a \
	  		$(CIRCLEHOME)/addon/vc4/interface/vcos/libvcos.a \
	  		$(CIRCLEHOME)/addon/vc4/vchiq/libvchiq.a \
#			$(CIRCLEHOME)/addon/vc4/vc_sm/libvc_sm.a \					
#			$(CIRCLEHOME)/addon/vc4/h264_decoder/libh264_decoder.a \   	
#			$(CIRCLEHOME)/addon/vc4/h264_parser/libh264_parser.a \ 		
			$(CIRCLEHOME)/addon/linux/liblinuxemu.a \
	  		$(CIRCLEHOME)/addon/sensor/libsensor.a \
	  		$(CIRCLEHOME)/addon/WS28XX/libws28xx.a
	  
include $(CIRCLEHOME)/Rules.mk

-include $(DEPS)