#
# Makefile
#

CIRCLEHOME = ../..

OBJS	= main.o kernel.o kernel_initialize.o kernel_run.o hardware.o logging.o CLogger.o

LIBS	= $(CIRCLEHOME)/lib/libcircle.a

include ../Rules.mk

-include $(DEPS)